### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by cslop3r** [eggplants/deepl-cli#155]
Hello, I'm getting this error since today:

```
Traceback (most recent call last):
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepl\deepl.py", line 141, in __transl
ate
    await page.wait_for_function(
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\async_api\_generated.py", l
ine 11720, in wait_for_function
    await self._impl_obj.wait_for_function(
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_page.py", line 957,
in wait_for_function
    return await self._main_frame.wait_for_function(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_frame.py", line 763,
 in wait_for_function
    return from_channel(await self._channel.send("waitForFunction", params))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line
 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line
 461, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line
 96, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.TimeoutError: Timeout 15000ms exceeded.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Nathan\Documents\RSL\index.py", line 73, in <module>
    title = deepl.translate(submission.title)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepl\deepl.py", line 85, in translate
    return loop.run_until_complete(self.__translate(script))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_comp
lete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepl\deepl.py", line 149, in __transl
ate
    raise DeepLCLIPageLoadError(msg) from e
deepl.deepl.DeepLCLIPageLoadError: Time limit exceeded. (15000 ms)
```

Please fix

**Comment by reddere** [comment]
same here! @eggplants

**Comment by eggplants** [comment]
Please try to increase the limit of timeout with `-t <ms>`. If it is not worked, retry translation.

Note that this tool translates by launching a web browser internally and directly manipulating the deepl WebUI.

Consider [using official API](https://github.com/DeepLcom/deepl-python) for stability.
