### ISSUE TITLE
An error occurs when the command is executed.

### ISSUE THREAD

**Issue by redpandabun** [eggplants/deepl-cli#192]
Hi, I am getting an error when running the CLI.

## Log
```
PS > "Flower Viewing" | deepl --fr en --to ko -t 60000 -s

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\deepl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\deepl\main.py", line 137, in main
    res = t.translate(script)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\deepl\deepl.py", line 85, in translate
    return loop.run_until_complete(self.__translate(script))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\deepl\deepl.py", line 121, in __translate
    await page.goto(f"{url}#{self.fr_lang}/{self.to_lang}/{script}")
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\playwright\async_api\_generated.py", line 9251, in goto
    await self._impl_obj.goto(
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\playwright\_impl\_page.py", line 473, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\playwright\_impl\_frame.py", line 138, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\playwright\_impl\_connection.py", line 490, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\playwright\_impl\_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Page closed
=========================== logs ===========================
navigating to "https://www.deepl.com/en/translator#en/ko/Flower%20Viewing", waiting until "load"
============================================================
```

## Environments
OS: Windows 11 Pro (22H2)
CPU: Intel i9-13900KS
Python: v3.11.6 (with Microsoft Store)
PIP: v23.3.1

**Comment by eggplants** [comment]
Latest test CI is faced with this issue. We need to investigate...

https://github.com/eggplants/deepl-cli/actions/runs/6853168937/job/18633392966?pr=191#step:6:324

**Comment by eggplants** [comment]
#221
