### ISSUE TITLE
offline handle

### ISSUE THREAD

**Issue by eggplants** [eggplants/deepl-cli#2]
In offline, 
```bash
$ deepl :zh <<<"hello"
Traceback (most recent call last):
  File "/home/eggplants/.pyenv/versions/3.8.0/bin/deepl", line 33, in <module>
    sys.exit(load_entry_point('deepl-cli', 'console_scripts', 'deepl')())
  File "/home/eggplants/prog/deepl-cli/deepl/main.py", line 6, in main
    print(t.translate())
  File "/home/eggplants/prog/deepl-cli/deepl/deepl.py", line 104, in translate
    input_area = d.find_element_by_xpath(
  File "/home/eggplants/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/eggplants/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/eggplants/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/eggplants/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//textarea[@dl-test="translator-source-input"]"}
  (Session info: headless chrome=83.0.4103.116)
```

**Comment by eggplants** [comment]
https://github.com/eggplants/deepl-cli/commit/ec90a1231ffb43a1f86228796183826de30faced
