### ISSUE TITLE
It doesn't work properly.

### ISSUE THREAD

**Issue by Zzz233** [eggplants/deepl-cli#27]
```python
Traceback (most recent call last):
  File "D:\DEV\ProjectCode\DeepL_trans\test.py", line 4, in <module>
    a = t.translate('hello')  # => 'こんにちわ'
  File "D:\DEV\new_antibody\venv310\lib\site-packages\deepl\deepl.py", line 140, in translate
    return asyncio.get_event_loop().run_until_complete(
  File "D:\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\DEV\new_antibody\venv310\lib\site-packages\deepl\deepl.py", line 145, in _translate
    browser: Browser = await launch(
  File "D:\DEV\new_antibody\venv310\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "D:\DEV\new_antibody\venv310\lib\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "D:\DEV\new_antibody\venv310\lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
```

**Comment by eggplants** [comment]
Somehow `deepl` works well except in 3.10. Please tell me your environment. (`uname -vorm && python -V`)

**Comment by eggplants** [comment]
This issue is maybe affected by this: https://github.com/pyppeteer/pyppeteer/issues/305

**Comment by eggplants** [comment]
I dropped 3.10 from supported python versions in de805972d62e677da4e8a7db256c0fa1cac99cf4.
Try in Python 3.5~3.9.

**Comment by Zzz233** [comment]
thank you
