### ISSUE TITLE
how to manually download the chromium engine 

### ISSUE THREAD

**Issue by nanderer** [eggplants/deepl-cli#32]
hi, i just got this problem:

```
ranslating...[W:pyppeteer.chromium_downloader] Starting Chromium download. Download may take a few minutes.
Traceback (most recent call last):
  File "/home/t/n/.local/bin/deepl", line 8, in <module>
    sys.exit(main())
  File "/home/t/n/.local/lib/python3.8/site-packages/deepl/main.py", line 13, in main
    result = t.translate(script)
  File "/home/t/n/.local/lib/python3.8/site-packages/deepl/deepl.py", line 140, in translate
    return asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/t/n/.local/lib/python3.8/site-packages/deepl/deepl.py", line 145, in _translate
    browser: Browser = await launch(
  File "/home/t/n/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/home/t/n/.local/lib/python3.8/site-packages/pyppeteer/launcher.py", line 120, in __init__
    download_chromium()
  File "/home/t/n/.local/lib/python3.8/site-packages/pyppeteer/chromium_downloader.py", line 139, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
  File "/home/t/n/.local/lib/python3.8/site-packages/pyppeteer/chromium_downloader.py", line 83, in download_zip
    raise OSError(f'Chromium downloadable not found at {url}: ' f'Received {r.data.decode()}.\n')
OSError: Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/588429/chrome-linux.zip: Received <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>.

^C

```

could you give me some hints how to manually download the engine (like where to put the zip file and so)?

thanks in advance
keep up the good work :)

**Comment by eggplants** [comment]
Are you using Proxy?

**Comment by nanderer** [comment]
no, its just not a rural connection but a server net...
```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 04:d4:c4:d2:68:9d brd ff:ff:ff:ff:ff:ff
    inet 116.202.128.144/32 scope global eno1
       valid_lft forever preferred_lft forever
    inet 178.63.180.185/29 brd 178.63.180.191 scope global eno1
       valid_lft forever preferred_lft forever
    inet6 2a01:4f8:231:482b::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::6d4:c4ff:fed2:689d/64 scope link 
       valid_lft forever preferred_lft forever
$ curl ifconfig.io 
116.202.128.144
$ 


```

**Comment by eggplants** [comment]
Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/588429/chrome-linux.zip:
Received
<?xml version='1.0' encoding='UTF-8'?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access denied.</Message>
    <Details>We're sorry, but this service is not available in your location</Details>
</Error>.
```

**Comment by eggplants** [comment]
Anyway, this issue depends on not deepl-cli but <https://github.com/pyppeteer/pyppeteer>.
Please report this to pyppeteer.

**Comment by nanderer** [comment]
thanks, ill do so but first i try 

```
$ tar cfvJ pyppeteer.tar.xz .local/share/pyppeteer
```
and then scp and untar it over there ;)

**Comment by nanderer** [comment]
btw, work around doing 

```
tar cfvJ pyppeteer.tar.xz .local/share/pyppeteer

```
copying to the other system and then doing

```
tar xfvJ /tmp/pyppeteer.tar.xz
```
worked fine ;)
