### ISSUE TITLE
Suddenly getting timeouts

### ISSUE THREAD

**Issue by lokeshh** [eggplants/deepl-cli#35]
I've been using deep-cli since last month. It's been working fine untill today. I started receiving these errors today-

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deepl/deepl.py", line 170, in _translate
    await page.waitForFunction('''
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyppeteer/frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for function failed: timeout 30000ms exceeds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "translate.py", line 17, in <module>
    res = t.translate(''.join(i))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deepl/deepl.py", line 140, in translate
    return asyncio.get_event_loop().run_until_complete(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deepl/deepl.py", line 179, in _translate
    raise DeepLCLIPageLoadError
deepl.deepl.DeepLCLIPageLoadError
```

Is there a way to increase the timeout?

**Comment by lokeshh** [comment]
Update: It's ocurring no more. Closing this now. I will reopen if it occurs again @eggplants

**Comment by lokeshh** [comment]
This is happening again. Is there a way to extend the timeout?
