### ISSUE TITLE
deepl-cli broken

### ISSUE THREAD

**Issue by Monsterovich** [eggplants/deepl-cli#46]
```
python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepl import deepl
>>> t = deepl.DeepLCLI("en", "ja")
>>> t.translate("hello") #=> "こんにちわ"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/monsterovich/.local/lib/python3.8/site-packages/deepl_cli-0.2.1-py3.8.egg/deepl/deepl.py", line 96, in translate
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/monsterovich/.local/lib/python3.8/site-packages/deepl_cli-0.2.1-py3.8.egg/deepl/deepl.py", line 161, in _translate
  File "/home/monsterovich/.local/lib/python3.8/site-packages/pyppeteer/page.py", line 1116, in evaluate
    return await frame.evaluate(pageFunction, *args, force_expr=force_expr)
  File "/home/monsterovich/.local/lib/python3.8/site-packages/pyppeteer/frame_manager.py", line 308, in evaluate
    return await context.evaluate(
  File "/home/monsterovich/.local/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 53, in evaluate
    handle = await self.evaluateHandle(
  File "/home/monsterovich/.local/lib/python3.8/site-packages/pyppeteer/execution_context.py", line 112, in evaluateHandle
    raise ElementHandleError('Evaluation failed: {}'.format(
pyppeteer.errors.ElementHandleError: Evaluation failed: TypeError: Cannot read property 'getAttribute' of null
    at __pyppeteer_evaluation_script__:2:80
```

**Comment by Monsterovich** [comment]
This fixed this error but the request freezes for some reason.

```
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepl import deepl
>>> t = deepl.DeepLCLI("en", "ja")
>>> t.translate("hello") #=> "こんにちわ"
Traceback (most recent call last):
  File "/home/monsterovich/Distfiles/compile/deepl-cli/deepl/deepl.py", line 142, in _translate
    await page.waitForFunction(
  File "/home/monsterovich/.local/lib/python3.8/site-packages/pyppeteer/frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for function failed: timeout 30000ms exceeds.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/monsterovich/Distfiles/compile/deepl-cli/deepl/deepl.py", line 96, in translate
    return asyncio.get_event_loop().run_until_complete(self._translate(script))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/monsterovich/Distfiles/compile/deepl-cli/deepl/deepl.py", line 148, in _translate
    raise DeepLCLIPageLoadError("Time limit exceeded. (30000ms)")
deepl.deepl.DeepLCLIPageLoadError: Time limit exceeded. (30000ms)
```

**Comment by eggplants** [comment]
Please try v0.2.3

**Comment by Monsterovich** [comment]
Works fine, thanks!
