### ISSUE TITLE
[0.2.3] Doesn't work if you use a file

### ISSUE THREAD

**Issue by Alimektor** [eggplants/deepl-cli#72]
Versions:

```bash
$ pip show deepl-cli
Name: deepl-cli
Version: 0.2.3
Summary: DeepL Translator CLI without API Key
Home-page: https://github.com/eggplants/deepl-cli
Author: eggplants
Author-email: w10776e8w@yahoo.co.jp
License: MIT
Location: /home/alimektor/.local/lib/python3/site-packages
Requires: pyppeteer
Required-by:
```

For example, I'm trying to configure my scripts to auto-translate.

```bash
$ echo "Hi, my name is Alimektor" >> hi.txt
$ deepl -f hi.txt --fr en --to zh
```

I get this:

```bash
Traceback (most recent call last):
  File "/home/alimektor/.local/bin/deepl", line 8, in <module>
    sys.exit(main())
  File "/home/alimektor/.local/lib/python3/site-packages/deepl/main.py", line 108, in main
    args = parse_args(test)
  File "/home/alimektor/.local/lib/python3/site-packages/deepl/main.py", line 102, in parse_args
    return parser.parse_args()
  File "/usr/lib64/python3.9/argparse.py", line 1818, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.9/argparse.py", line 2060, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.9/argparse.py", line 2000, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.9/argparse.py", line 1912, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib64/python3.9/argparse.py", line 2443, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib64/python3.9/argparse.py", line 2476, in _get_value
    result = type_func(arg_string)
  File "/home/alimektor/.local/lib/python3/site-packages/deepl/main.py", line 30, in check_file
    elif not is_binary_string(cast(bytes, open(v, "rb"))):
  File "/home/alimektor/.local/lib/python3/site-packages/deepl/main.py", line 25, in is_binary_string
    return bool(b.translate(None, textchars))
AttributeError: '_io.BufferedReader' object has no attribute 'translate'
```

I'll try to see for myself later to see what's going on here.

**Comment by Alimektor** [comment]
Corrected it myself, I'll send the PR a little later. Found some more errors.
