### ISSUE TITLE
Handle timeout while running CLI

### ISSUE THREAD

**Issue by eggplants** [eggplants/deepl-cli#82]
`deepl.deepl.DeepLCLIPageLoadError`

**Comment by eggplants** [comment]
```shellsession
$ deepl --to fr -s <<<"hello! I'm eggplants."
```
```python
Traceback (most recent call last):
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/deepl/deepl.py", line 108, in __translate
    await page.wait_for_function(
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 11331, in wait_for_function
    await self._impl_obj.wait_for_function(
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/playwright/_impl/_page.py", line 946, in wait_for_function
    return await self._main_frame.wait_for_function(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 763, in wait_for_function
    return from_channel(await self._channel.send("waitForFunction", params))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: TypeError: Cannot read properties of null (reading 'value')
    at eval (eval at predicate (eval at evaluate (:197:30)), <anonymous>:2:65)
    at predicate (eval at evaluate (:197:30), <anonymous>:15:54)
    at eval (eval at evaluate (:197:30), <anonymous>:19:82)
    at next (<anonymous>:4533:27)
    at <anonymous>:4543:7
    at Object.run (<anonymous>:4587:22)
    at eval (eval at evaluate (:197:30), <anonymous>:1:14)
    at UtilityScript.evaluate (<anonymous>:199:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
=========================== logs ===========================
  Cannot read properties of null (reading 'value')
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eggplants/.pyenv/versions/3.11.0/bin/deepl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/deepl/main.py", line 144, in main
    res = t.translate(script)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/deepl/deepl.py", line 73, in translate
    return asyncio.run(self.__translate(script))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/eggplants/.pyenv/versions/3.11.0/lib/python3.11/site-packages/deepl/deepl.py", line 126, in __translate
    raise DeepLCLIPageLoadError(
deepl.deepl.DeepLCLIPageLoadError: Time limit exceeded. (5000 ms, TypeError: Cannot read properties of null (reading 'value')
    at eval (eval at predicate (eval at evaluate (:197:30)), <anonymous>:2:65)
    at predicate (eval at evaluate (:197:30), <anonymous>:15:54)
    at eval (eval at evaluate (:197:30), <anonymous>:19:82)
    at next (<anonymous>:4533:27)
    at <anonymous>:4543:7
    at Object.run (<anonymous>:4587:22)
    at eval (eval at evaluate (:197:30), <anonymous>:1:14)
    at UtilityScript.evaluate (<anonymous>:199:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
=========================== logs ===========================
  Cannot read properties of null (reading 'value')
============================================================)
```
